apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: kube-prometheus/crds
    repoURL: 'https://github.com/kaytalkcity/eks.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true